# Resize selected screenshots for the README into docs/images/.
# Keeps the repository small: each image is scaled to a fixed width and re-encoded as JPEG.
# Source screenshots live in artifacts/ (git-ignored) and are regenerated by the capture scripts.
Add-Type -AssemblyName System.Drawing

$root = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $root 'docs\images'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

# name -> source path relative to artifacts/
$pick = [ordered]@{
    'home'            = 'app\32-final.png'
    'wardrobe'        = 'demo\04-wardrobe-list.png'
    'import-page'     = 'a-20-import-page.png'
    'picker'          = 'a-04-picker.png'
    'diy-canvas'      = 'demo\06-outfit-page.png'
    'canvas-export'   = 'canvas-export-preview.png'
    'outfit-detail'   = 'demo\05-garment-detail.png'
    'diary'           = 'dev-diary.png'
    'profile'         = 'demo\07-profile-page.png'
    'tryon'           = 'tryon-demo\tryon-final.png'
}

$targetWidth = 540
$quality = 82

$jpegCodec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() |
    Where-Object { $_.MimeType -eq 'image/jpeg' }
$encoderParams = New-Object System.Drawing.Imaging.EncoderParameters(1)
$encoderParams.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter(
    [System.Drawing.Imaging.Encoder]::Quality, [int64]$quality)

foreach ($name in $pick.Keys) {
    $src = Join-Path $root ('artifacts\' + $pick[$name])
    if (-not (Test-Path $src)) { Write-Output ("MISSING  {0}  <- {1}" -f $name, $pick[$name]); continue }
    $img = [System.Drawing.Image]::FromFile($src)
    try {
        $ratio = $targetWidth / $img.Width
        $w = $targetWidth
        $h = [int][Math]::Round($img.Height * $ratio)
        $bmp = New-Object System.Drawing.Bitmap($w, $h)
        try {
            $g = [System.Drawing.Graphics]::FromImage($bmp)
            try {
                $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
                $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
                $g.DrawImage($img, 0, 0, $w, $h)
            } finally { $g.Dispose() }
            $dest = Join-Path $outDir ($name + '.jpg')
            $bmp.Save($dest, $jpegCodec, $encoderParams)
            Write-Output ("OK  {0,-15} {1}x{2}  {3,6:N1} KB   (from {4})" -f `
                $name, $w, $h, ((Get-Item $dest).Length / 1KB), $pick[$name])
        } finally { $bmp.Dispose() }
    } finally { $img.Dispose() }
}
Write-Output ''
Write-Output ('总大小: {0:N1} KB' -f ((Get-ChildItem $outDir -File | Measure-Object Length -Sum).Sum / 1KB))
